#!/bin/bash
#####nova add-secgroup qacass-fxbo-01.sys.comcast.net jumphost
#####nova add-secgroup qacass-fxbo-02.sys.comcast.net jumphost
#####nova add-secgroup qacass-fxbo-03.sys.comcast.net jumphost
#####nova add-secgroup qamedia-fxbo-01.sys.comcast.net jumphost
#####nova add-secgroup qamedia-fxbo-02.sys.comcast.net jumphost
#####nova add-secgroup qamedia-fxbo-02.sys.comcast.net jumphost
#####nova add-secgroup qaugc-fxbo-01.sys.comcast.net jumphost
#####nova add-secgroup qaugc-fxbo-02.sys.comcast.net jumphost
#####nova add-secgroup qaugcdoc-fxbo-01.sys.comcast.net jumphost
#####nova add-secgroup qaxproxy-fxbo-01.sys.comcast.net jumphost
#####nova add-secgroup qaxproxy-fxbo-02.sys.comcast.net jumphost
####nova add-secgroup  qacass-wbrn-01.sys.comcast.net    jumphost
####nova add-secgroup  qacass-wbrn-02.sys.comcast.net    jumphost
####nova add-secgroup  qacass-wbrn-03.sys.comcast.net    jumphost
####nova add-secgroup  qamedia-wbrn-01.sys.comcast.net   jumphost
####nova add-secgroup  qamedia-wbrn-02.sys.comcast.net   jumphost
####nova add-secgroup  qaugc-wbrn-01.sys.comcast.net     jumphost
####nova add-secgroup  qaugc-wbrn-02.sys.comcast.net     jumphost
####nova add-secgroup  qaugcdoc-wbrn-01.sys.comcast.net  jumphost
####nova add-secgroup  qaxproxy-wbrn-01.sys.comcast.net  jumphost
####nova add-secgroup  qaxproxy-wbrn-02.sys.comcast.net  jumphost
###nova add-secgroup  cass-fxbo-01.sys.comcast.net        jumphost
###nova add-secgroup  cass-fxbo-02.sys.comcast.net        jumphost
###nova add-secgroup  cass-fxbo-03.sys.comcast.net        jumphost
###nova add-secgroup  media-fxbo-01.sys.comcast.net       jumphost
###nova add-secgroup  media-fxbo-02.sys.comcast.net       jumphost
###nova add-secgroup  ugc-fxbo-01.sys.comcast.net         jumphost
###nova add-secgroup  ugc-fxbo-02.sys.comcast.net         jumphost
###nova add-secgroup  ugcdocs-fxbo-01.sys.comcast.net     jumphost
###nova add-secgroup  ugchaproxy-fxbo-01.sys.comcast.net  jumphost
###nova add-secgroup  ugchaproxy-fxbo-02.sys.comcast.net  jumphost
##nova add-secgroup  cass-wbrn-01.sys.comcast.net        jumphost
##nova add-secgroup  cass-wbrn-02.sys.comcast.net        jumphost
##nova add-secgroup  cass-wbrn-03.sys.comcast.net        jumphost
##nova add-secgroup  media-wbrn-01.sys.comcast.net       jumphost
##nova add-secgroup  media-wbrn-02.sys.comcast.net       jumphost
##nova add-secgroup  ugc-wbrn-01.sys.comcast.net         jumphost
##nova add-secgroup  ugc-wbrn-02.sys.comcast.net         jumphost
##nova add-secgroup  ugcdocs-wbrn-01.sys.comcast.net     jumphost
##nova add-secgroup  ugchaproxy-wbrn-01.sys.comcast.net  jumphost
##nova add-secgroup  ugchaproxy-wbrn-02.sys.comcast.net  jumphost
#nova add-secgroup  intcass-emhr-01.sys.comcast.net     jumphost
#nova add-secgroup  intcass-emhr-02.sys.comcast.net     jumphost
#nova add-secgroup  intcass-emhr-03.sys.comcast.net     jumphost
#nova add-secgroup  intmedia-emhr-01.sys.comcast.net    jumphost
#nova add-secgroup  intmedia-emhr-02.sys.comcast.net    jumphost
#nova add-secgroup  intugc-emhr-01.sys.comcast.net      jumphost
#nova add-secgroup  intugc-emhr-02.sys.comcast.net      jumphost
#nova add-secgroup  intugcdocs-emhr-01.sys.comcast.net  jumphost
#nova add-secgroup  intxproxy-emhr-01.sys.comcast.net   jumphost
#nova add-secgroup  intxproxy-emhr-02.sys.comcast.net   jumphost
#nova add-secgroup  netopuppet-test                     jumphost
nova add-secgroup  intcass-area4-01.sys.comcast.net     jumphost
nova add-secgroup  intcass-area4-02.sys.comcast.net     jumphost
nova add-secgroup  intcass-area4-03.sys.comcast.net     jumphost
nova add-secgroup  intmedia-area4-01.sys.comcast.net    jumphost
nova add-secgroup  intmedia-area4-02.sys.comcast.net    jumphost
nova add-secgroup  intugc-area4-01.sys.comcast.net      jumphost
nova add-secgroup  intugc-area4-02.sys.comcast.net      jumphost
nova add-secgroup  intugcdocs-area4-01.sys.comcast.net  jumphost
nova add-secgroup  intxproxy-area4-01.sys.comcast.net   jumphost
nova add-secgroup  intxproxy-area4-02.sys.comcast.net   jumphost
