nova rename intrugc-area4-01.sys.comcast.net intugc-area4-01.sys.comcast.net
nova rename intrugc-area4-02.sys.comcast.net intugc-area4-02.sys.comcast.net
nova rename intrmedia-area4-01.sys.comcast.net intmedia-area4-01.sys.comcast.net
nova rename intrmedia-area4-02.sys.comcast.net intmedia-area4-02.sys.comcast.net
nova rename intrxproxy-area4-01.sys.comcast.net intxproxy-area4-01.sys.comcast.net
nova rename intrxproxy-area4-02.sys.comcast.net intxproxy-area4-02.sys.comcast.net
nova rename intrcass-area4-01.sys.comcast.net intcass-area4-01.sys.comcast.net
nova rename intrcass-area4-02.sys.comcast.net intcass-area4-02.sys.comcast.net
nova rename intrcass-area4-03.sys.comcast.net intcass-area4-03.sys.comcast.net
#nova rename intrugcdocs-area4-01.sys.comcast.net intugcdocs-area4-01.sys.comcast.net

#nova rename intrugc-emhr-01.sys.comcast.net intugc-emhr-01.sys.comcast.net
#nova rename intrugc-emhr-02.sys.comcast.net intugc-emhr-02.sys.comcast.net
#nova rename intrmedia-emhr-01.sys.comcast.net intmedia-emhr-01.sys.comcast.net
#nova rename intrmedia-emhr-02.sys.comcast.net intmedia-emhr-02.sys.comcast.net
#nova rename intrxproxy-emhr-01.sys.comcast.net intxproxy-emhr-01.sys.comcast.net
#nova rename intrxproxy-emhr-02.sys.comcast.net intxproxy-emhr-02.sys.comcast.net
#nova rename intrcass-emhr-01.sys.comcast.net intcass-emhr-01.sys.comcast.net
#nova rename intrcass-emhr-02.sys.comcast.net intcass-emhr-02.sys.comcast.net
#nova rename intrcass-emhr-03.sys.comcast.net intcass-emhr-03.sys.comcast.net
#nova rename intrugcdocs-emhr-01.sys.comcast.net intugcdocs-emhr-01.sys.comcast.net
